### ISSUE TITLE
This is my old junk code

### ISSUE THREAD

**Issue by 0xffffa** [xvertile/akamai-bmp-generator#10]
To anyone going to use this, the original creator of the project isn't the person who posted it or linked in the description, its me. And I can promise you that this will NOT work for ANY akamai bmp site for more than a few thousand requests.

This is due to the events, and only the events. Akamai bmp engineers did an excellent job at blocking artificial events, so if you've even thought about using this, most likely you are not skilled enough to bypass akamai bmp even with a 70% accuracy rate. 

This is actual garbage, you would quite LITERALLY be better off sending empty events.

**Comment by xvertile** [comment]
OP is right this public project is not perfect and will not work at scale.
I merely made the code pubic hoping that others with more knowledge could
improve upon it but sadly this has not happened yet. If you wish for me to
link you in the readme please let me know many have claimed authorship so
at this point I have no clue who actually made it. But you are correct the
events are randomly generated and the device list is very small.

Again this project is not a full solution it needs to be improved and
updated, how ever this is atleast a base and contains allot of helper
functions that could be used to create a better and more scalable solution.
Again if you wish me to link to any site in the readme please let me know.
Credit where credit is due.
