### ISSUE TITLE
Bit late for a skid mate...

### ISSUE THREAD

**Issue by ui0x** [xvertile/akamai-bmp-generator#7]
![image](https://github.com/xvertile/akamai-bmp-generator/assets/139102100/8764eb23-8d04-4192-95c2-fad20db8c43d)

Happy to share 3.3.5 with you if you want to include that in your "improved version" of our code lol. 

Love it.

**Comment by ui0x** [comment]
Thanks for sharing it with everyone though! Love the support. x

**Comment by GuiKlesseMiranda** [comment]
There is 3.3.8 too

**Comment by GuiKlesseMiranda** [comment]
it adds -163 and -164 params

**Comment by xvertile** [comment]
I reached out to you you said you wanted nothing to do with it and to remove all references. I have updated the readme with credit let me know if you want to link grimoir.cc

**Comment by Wang1998** [comment]
Can you share 3.3.5?
